name: Shapes Demo Ubuntu CI reusable workflow

on:
  workflow_call:
    inputs:
      os-version:
        description: 'The OS image for the workflow'
        required: false
        default: 'ubuntu-22.04'
        type: string
      label:
        description: 'ID associated to the workflow'
        required: true
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      shapes-demo-branch:
        description: 'Branch or tag of Shapes Demo repository'
        required: true
        type: string
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository'
        required: true
        type: string
      run-build:
        description: 'Build Shapes Demo (CI skipped otherwise)'
        required: false
        type: boolean
        default: true
      use-ccache:
        description: 'Use CCache to speed up the build'
        required: false
        type: boolean
        default: false
env:
    colcon-build-default-cmake-args: '-DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra -Wpedantic -Wunused-value -Woverloaded-virtual"'
defaults:
  run:
    shell: bash

jobs:
  shapes_demo_build:
    runs-on: ${{ inputs.os-version }}
    if: ${{ inputs.run-build == true }}
    strategy:
      fail-fast: false
      matrix:
        cmake-build-type:
          - 'RelWithDebInfo'
    steps:
      - name: Add ci-pending label if PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: eProsima/eProsima-CI/external/add_labels@v0
        with:
          labels: ci-pending
          number: ${{ github.event.number }}
          repo: eProsima/ShapesDemo

      - name: Sync eProsima/ShapesDemo repository
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          path: src/ShapesDemo
          ref: ${{ inputs.shapes-demo-branch }}

      - name: Install Fix Python version
        uses: eProsima/eProsima-CI/external/setup-python@v0
        with:
          python-version: '3.11'

      - name: Get minimum supported version of CMake
        uses: eProsima/eProsima-CI/external/get-cmake@v0
        with:
          cmakeVersion: '3.22.6'

      - name: Install apt dependencies
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
        with:
          packages: libasio-dev libtinyxml2-dev libssl-dev
          update: false
          upgrade: false

      - name: Install colcon
        uses: eProsima/eProsima-CI/ubuntu/install_colcon@v0

      - name: Install Python dependencies
        uses: eProsima/eProsima-CI/multiplatform/install_python_packages@v0
        with:
          packages: vcstool xmlschema
          upgrade: false

      # Do not setup python as it will internally modify the pythonLocation env variable
      # and we want to use a fix version
      - name: Install Qt
        uses: eProsima/eProsima-CI/external/install_qt@v0
        with:
          version: '5.15.2'
          dir: '${{ github.workspace }}/qt_installation/'
          modules: 'qtcharts'
          setup-python: 'false'

      - name: Setup CCache
        uses: eProsima/eProsima-CI/external/setup-ccache-action@v0
        if: ${{ inputs.use-ccache == true }}
        with:
          api_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Fast DDS branch
        id: get_fastdds_branch
        uses: eProsima/eProsima-CI/ubuntu/get_related_branch_from_repo@v0
        with:
          remote_repository: eProsima/Fast-DDS
          fallback_branch: ${{ inputs.fastdds-branch }}

      - name: Download Fast DDS repo
        uses: eProsima/eProsima-CI/external/checkout@v0
        with:
          repository: eProsima/Fast-DDS
          path: src/fastdds
          ref: ${{ steps.get_fastdds_branch.outputs.deduced_branch }}

      - name: Fetch Fast DDS dependencies
        uses: eProsima/eProsima-CI/multiplatform/vcs_import@v0
        with:
          vcs_repos_file: ${{ github.workspace }}/src/fastdds/fastdds.repos
          destination_workspace: src
          skip_existing: 'true'

      - name: Colcon build
        continue-on-error: false
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0
        with:
          colcon_meta_file: ${{ github.workspace }}/src/ShapesDemo/.github/workflows/config/build.meta
          colcon_build_args: ${{ inputs.colcon-args }}
          colcon_build_args_default: --event-handlers=console_direct+
          cmake_args: ${{ inputs.cmake-args }}
          cmake_args_default: ${{ env.colcon-build-default-cmake-args }}
          cmake_build_type: ${{ matrix.cmake-build-type }}
          workspace: ${{ github.workspace }}
