
name: Shapes Demo Ubuntu CI

on:
  workflow_dispatch:
    inputs:
      os-version:
        description: 'OS version to run the workflow'
        required: false
        default: 'ubuntu-22.04'
        type: string
      colcon-args:
        description: 'Extra arguments for colcon cli'
        required: false
        type: string
      cmake-args:
        description: 'Extra arguments for cmake cli'
        required: false
        type: string
      ctest-args:
        description: 'Extra arguments for ctest cli'
        required: false
        type: string
      shapes-demo-branch:
        description: 'Branch or tag of Shapes Demo repository'
        type: string
        required: true
      fastdds-branch:
        description: 'Branch or tag of Fast DDS repository'
        type: string
        required: true
      use-ccache:
        description: 'Use CCache to speed up the build'
        required: false
        type: boolean
        default: false

  pull_request:
    types:
      - review_requested
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-ci:
    uses: ./.github/workflows/reusable-ubuntu-ci.yml
    with:
      os-version: ${{ inputs.os-version || 'ubuntu-22.04' }}
      label: 'ubuntu-ci'
      colcon-args: ${{ inputs.colcon-args }}
      cmake-args: ${{ inputs.cmake-args }}
      ctest-args: ${{ inputs.ctest-args }}
      shapes-demo-branch: ${{ inputs.shapes-demo-branch || github.ref || 'master' }}
      fastdds-branch: ${{ inputs.fastdds-branch || 'master' }}
      run-build: ${{ !(github.event_name == 'pull_request') && true || (!contains(github.event.pull_request.labels.*.name, 'skip-ci') && !contains(github.event.pull_request.labels.*.name, 'conflicts')) && true || false }}
      use-ccache: ${{ inputs.use-ccache || false }}
