name: Shapes Demo Ubuntu CI (weekly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run at minute 0 on Monday

jobs:
  weekly-ubuntu-ci-2_6_x:
    uses: eProsima/ShapesDemo/.github/workflows/reusable-ubuntu-ci.yml@2.6.x
    with:
      os-version: 'ubuntu-20.04'
      label: 'weekly-ubuntu-ci-2.6.x'
      shapes-demo-branch: '2.6.x'
      fastdds-branch: '2.6.x'
      run-build: true
      use-ccache: false
